use SHOPDACSAN
go
-------------------------------


/**********NHA CUNG CAP****************/
INSERT NHACUNGCAP (MANCC, TENNCC, DIACHINCC, DTNCC, EMAILNCC, MASOTHUE, GHICHU)
VALUES ('', N'BÍCH CHI', '', '02773 861 910', '', '', '')
INSERT NHACUNGCAP (MANCC, TENNCC, DIACHINCC, DTNCC, EMAILNCC, MASOTHUE, GHICHU)
VALUES ('', N'SA GIANG', '' , '02773 763 155', '', '', '')
INSERT NHACUNGCAP (MANCC, TENNCC, DIACHINCC, DTNCC, EMAILNCC, MASOTHUE, GHICHU)
VALUES ('', N'TỨ QUÝ', '', '0918 426 449', '', '', '')
INSERT NHACUNGCAP (MANCC, TENNCC, DIACHINCC, DTNCC, EMAILNCC, MASOTHUE, GHICHU)
VALUES ('', N'NAM HUY', '', '0933 758 660', '', '', '')
INSERT NHACUNGCAP (MANCC, TENNCC, DIACHINCC, DTNCC, EMAILNCC, MASOTHUE, GHICHU)
VALUES ('', N'BẢY NỮA', '', '0987 143 057', '', '' ,'')
INSERT NHACUNGCAP (MANCC, TENNCC, DIACHINCC, DTNCC, EMAILNCC, MASOTHUE, GHICHU)
VALUES ('', N'NƯỚC MẮM HỒNG NGỰ', '', '0918 663 900', '', '', '')
INSERT NHACUNGCAP (MANCC, TENNCC, DIACHINCC, DTNCC, EMAILNCC, MASOTHUE, GHICHU)
VALUES ('', N'ĐỒNG THÁP MƯỜI', '', '0123 6900 666', '', '' ,'')
INSERT NHACUNGCAP (MANCC, TENNCC, DIACHINCC, DTNCC, EMAILNCC, MASOTHUE, GHICHU)
VALUES ('', N'KHÔ ĐIÊU HỒNG', '', '0939 376 299', '', '', '')
INSERT NHACUNGCAP (MANCC, TENNCC, DIACHINCC, DTNCC, EMAILNCC, MASOTHUE, GHICHU)
VALUES ('', N'TƯ BÔNG', '', '0906 834 247', '', '', '')
INSERT NHACUNGCAP (MANCC, TENNCC, DIACHINCC, DTNCC, EMAILNCC, MASOTHUE, GHICHU)
VALUES ('', N'RANEE', '', '0939 414 286', '', '', '')
INSERT NHACUNGCAP (MANCC, TENNCC, DIACHINCC, DTNCC, EMAILNCC, MASOTHUE, GHICHU)
VALUES ('', N'GẠO CỎ MAY', '', '0949 661 188', '', '', '')
INSERT NHACUNGCAP (MANCC, TENNCC, DIACHINCC, DTNCC, EMAILNCC, MASOTHUE, GHICHU)
VALUES ('', N'CÔNG TY LƯƠNG THỰC', '', '0918 555 958', '', '', '')
INSERT NHACUNGCAP (MANCC, TENNCC, DIACHINCC, DTNCC, EMAILNCC, MASOTHUE, GHICHU)
VALUES ('', N'SÂM NGỌC LINH', '', '02773 661 818', '', '', '')
INSERT NHACUNGCAP (MANCC, TENNCC, DIACHINCC, DTNCC, EMAILNCC, MASOTHUE, GHICHU)
VALUES ('', N'KHÔ TRÂU', '', '0123 2005 886', '', '', '')
INSERT NHACUNGCAP (MANCC, TENNCC, DIACHINCC, DTNCC, EMAILNCC, MASOTHUE, GHICHU)
VALUES ('', N'CÔNG TY HƯƠNG SEN VIỆT', '', '0949 678 338', '', '', '')
INSERT NHACUNGCAP (MANCC, TENNCC, DIACHINCC, DTNCC, EMAILNCC, MASOTHUE, GHICHU)
VALUES ('', N'MUỐI SẤY NGỌC YẾN', '', '0918 332 487', '', '', '')

INSERT NHACUNGCAP (MANCC, TENNCC, DIACHINCC, DTNCC, EMAILNCC, MASOTHUE, GHICHU)
VALUES ()


/**********SAN PHAM***********/
/******************BICH CHI******************/
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Bánh phồng Gạo Lứt 200gr', N'Bánh Phồng', 0, 'NCC0001', N'Hộp', 16000, 17000, 'banh phong gao lut.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Bánh phồng Cá Lăng', N'Bánh Phồng', 0, 'NCC0001', N'Hộp', 50000, 55000, 'banh phong ca lang.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Bún Tươi', N'Bún', 0, 'NCC0001', N'Gói', 11000, 12000, 'bun tuoi.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Hủ Tiếu Bột Lọc', N'Bún', 0, 'NCC0001', N'Gói', 11000, 12000, 'hu tieu bot loc.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Bún Gạo Lứt Huyết Rồng', N'Bún', 0, 'NCC0001', N'Gói', 12000, 13000, 'bun gao lut huyet rong.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Miến Đậu Xanh', N'Bún', 0, 'NCC0001', N'Gói', 18000, 20000, 'mien dau xanh.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Bánh phồng Tảo 200gr', N'Bánh Phồng', 0, 'NCC0001', N'Hộp', 17000, 18000, 'banh phong tao.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Bột Đậu Xanh Hạt Sen 300gr', N'Bột', 0, 'NCC0001', N'Gói', 24000, 25000, 'bot dau xanh het sen.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Bột Gạo Lứt Hạt Sen 300gr', N'Bột', 0, 'NCC0001', N'Gói', 24000, 25000, 'bot gao lut hat sen.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Bột Mè Đen Hạt Sen 300gr', N'Bột', 0, 'NCC0001', N'Gói', 27000, 28000, 'bot me den hat sen.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Bột 5 Thứ Đậu Hạt Sen 300gr', N'Bột', 0, 'NCC0001', N'Gói', 24000, 25000, 'bot 5 thu dau hat sen.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Bột Đậu Nành Hạt Sen 300gr', N'Bột', 0, 'NCC0001', N'Gói', 24000, 25000, 'bot dau nang hat sen.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Bột Đậu Xanh Đen Lòng 300gr', N'Bột', 0, 'NCC0001', N'Gói', 27000, 28000, 'bot dau den xanh long.jpg')

/*********************SA GIANG*************************/
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Bánh phồng tôm Cao Cấp - Tròn 500gr', N'Bánh Phồng', 0, 'NCC0002', N'Hộp', 0, 0, 'banh phong tom cao cap SG tron.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Bánh phồng tôm khoai lang - 200gr', N'Bánh Phồng', 0, 'NCC0002', N'Hộp', 0, 0, 'banh phong tom khoai lang.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Bánh phồng tôm Cao Cấp - Vuông 500gr', N'Bánh Phồng', 0, 'NCC0002', N'Hộp', 0, 0, 'banh phong tom cao cap SG vuong.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Bánh phồng tôm Thượng hạng 200gr', N'Bánh Phồng', 0, 'NCC0002', N'Hộp', 0, 0, 'banh phong tom thuong hang.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Bánh phồng tôm đặc biệt 200gr', N'Bánh Phồng', 0, 'NCC0002', N'Hộp', 0, 0, 'banh phong tom dac biet.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Bánh phồng tôm vuông 400gr', N'Bánh Phồng', 0, 'NCC0002', N'Hộp', 0, 0, 'banh phong tom vuong.jpg')

/*******************TỨ QUÝ*****************************/
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Khô Sặc Tứ Quý 400gr', N'Khô', 0, 'NCC0003', N'Gói', 0, 0, 'kho sac tu quy.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Khô Lóc Tứ Quý 400gr', N'Khô', 0, 'NCC0003', N'Gói', 0, 0, 'kho loc tu quy.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Chả Cá Lóc - Khối 250gr', N'Chả', 0, 'NCC0003', N'Gói', 0, 0, 'cha co loc.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Chả Cá Lóc - Khối 500gr', N'Chả', 0, 'NCC0003', N'Gói', 0, 0, 'cha ca loc.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Chả Cá Lóc - Viên 250gr', N'Chả', 0, 'NCC0003', N'Gói', 0, 0, 'cha ca loc.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Chả Cá Lóc - Viên 500gr', N'Chả', 0, 'NCC0003', N'Gói', 0, 0, 'cha ca loc.jpg')

/*******************NAM HUY*******************************/
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Sen Sấy 500gr', N'SP Sấy', 0, 'NCC0004', N'Gói', 0, 0, 'sen say 500gr.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Sen Sấy 40gr', N'SP Sấy', 0, 'NCC0004', N'Gói', 0, 0, 'sen say 40gr.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Mít Sấy 40gr', N'SP Sấy', 0, 'NCC0004', N'Gói', 0, 0, 'mit say 40gr.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Mít Sấy 80gr', N'SP Sấy', 0, 'NCC0004', N'Gói', 0, 0, 'mit say 80gr.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Trái Cây Sấy 80gr', N'SP Sấy', 0, 'NCC0004', N'Gói', 0, 0, 'trai cay say 80gr.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Sen Sấy 100gr', N'SP Sấy', 0, 'NCC0004', N'Hộp', 0, 0, 'sen say 100gr.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Sen Sấy 200gr', N'SP Sấy', 0, 'NCC0004', N'Hộp', 0, 0, 'sen say 200gr.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Khoai Lang Sấy 80gr', N'SP Sấy', 0, 'NCC0004', N'Gói', 0, 0, 'khoai lang say 80gr.jpg')

/*************************BẢY NỮA****************************/
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Khô Ếch 200gr', N'Khô', 0, 'NCC0005', N'Gói', 0, 0, 'kho ech.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Chà Bông Ếch 95gr', N'Chà Bông', 0, 'NCC0005', N'Hộp', 0, 0, 'cha bong ech.jpg')
INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES('', N'Chà Bông Ếch 65gr', N'Chà Bông', 0, 'NCC0005', N'Hộp', 0, 0, 'cha bong ech.jpg')

/************************NƯỚC MẮM HỒNG NGỰ**********************/
INSERT [dbo].[SANPHAM] ([MASP], [TENSP], [LOAI], [SOLUONG], [MANCC], [DONVITINH], [GIAVON], [GIABAN], [HINHANH]) 
VALUES ('', N'Nước mắm Hồng Ngự', N'Nước Mắm', 0, N'NCC0006', N'Hộp', CAST(95000 AS Decimal(18, 0)), CAST(100000 AS Decimal(18, 0)), N'nuoc mam hong ngu.jpg')

/************************ĐỒNG THÁP MƯỜI*************************/
INSERT [dbo].[SANPHAM] ([MASP], [TENSP], [LOAI], [SOLUONG], [MANCC], [DONVITINH], [GIAVON], [GIABAN], [HINHANH]) 
VALUES ('', N'Rượu Hồng Sen Tửu Đặc Biệt 1000ml', N'Rượu', 0, N'NCC0007', N'Chai', CAST(850000 AS Decimal(18, 0)), CAST(900000 AS Decimal(18, 0)), N'hst dac biet.jpg')
INSERT [dbo].[SANPHAM] ([MASP], [TENSP], [LOAI], [SOLUONG], [MANCC], [DONVITINH], [GIAVON], [GIABAN], [HINHANH]) 
VALUES ('', N'Rượu Hồng Sen Tửu 750ml', N'Rượu', 0, N'NCC0007', N'chai', CAST(160000 AS Decimal(18, 0)), CAST(165000 AS Decimal(18, 0)), N'hst.jpg')
INSERT [dbo].[SANPHAM] ([MASP], [TENSP], [LOAI], [SOLUONG], [MANCC], [DONVITINH], [GIAVON], [GIABAN], [HINHANH]) 
VALUES ('', N'Rượu Hồng Sen Tửu 500ml', N'Rượu', 0, N'NCC0007', N'Chai', CAST(100000 AS Decimal(18, 0)), CAST(110000 AS Decimal(18, 0)), N'hst.jpg')
INSERT [dbo].[SANPHAM] ([MASP], [TENSP], [LOAI], [SOLUONG], [MANCC], [DONVITINH], [GIAVON], [GIABAN], [HINHANH]) 
VALUES ('', N'Rượu Hồng Sen Tửu 300ml', N'Rượu', 0, N'NCC0007', N'Chai', CAST(60000 AS Decimal(18, 0)), CAST(65000 AS Decimal(18, 0)), N'hst.jpg')

/************************KHÔ CÁ ĐIÊU HỒNG***************************/
INSERT [dbo].[SANPHAM] ([MASP], [TENSP], [LOAI], [SOLUONG], [MANCC], [DONVITINH], [GIAVON], [GIABAN], [HINHANH]) 
VALUES ('', N'Khô Cá Điêu Hồng 200gr', N'Khô', 0, N'NCC0008', N'Gói', CAST(68000 AS Decimal(18, 0)), CAST(70000 AS Decimal(18, 0)), N'kho dieu hong hai yen.jpg')

/************************TƯ BÔNG**************************************/
INSERT [dbo].[SANPHAM] ([MASP], [TENSP], [LOAI], [SOLUONG], [MANCC], [DONVITINH], [GIAVON], [GIABAN], [HINHANH]) 
VALUES ('', N'Mứt Khóm 220gr', N'Mứt', 0, N'NCC0009', N'Hộp', CAST(38000 AS Decimal(18, 0)), CAST(40000 AS Decimal(18, 0)), N'mut khom.jpg')
INSERT [dbo].[SANPHAM] ([MASP], [TENSP], [LOAI], [SOLUONG], [MANCC], [DONVITINH], [GIAVON], [GIABAN], [HINHANH]) 
VALUES ('', N'Mứt Chuối Phồng Mè 220gr', N'Mứt', 0, N'NCC0009', N'Hộp', CAST(33000 AS Decimal(18, 0)), CAST(35000 AS Decimal(18, 0)), N'mut chuoi phong me 220gr.jpg')
INSERT [dbo].[SANPHAM] ([MASP], [TENSP], [LOAI], [SOLUONG], [MANCC], [DONVITINH], [GIAVON], [GIABAN], [HINHANH]) 
VALUES ('', N'Mứt Chuối Phồng Hạt Điều 220gr', N'Mứt', 0, N'NCC0009', N'Hộp', CAST(33000 AS Decimal(18, 0)), CAST(35000 AS Decimal(18, 0)), N'mut chuoi phong hat dieu 220gr.jpg')
INSERT [dbo].[SANPHAM] ([MASP], [TENSP], [LOAI], [SOLUONG], [MANCC], [DONVITINH], [GIAVON], [GIABAN], [HINHANH]) 
VALUES ('', N'Mứt Chuối Phòng Hạt Điều 170gr', N'Mứt', 0, N'NCC0009', N'Hộp', CAST(31000 AS Decimal(18, 0)), CAST(32000 AS Decimal(18, 0)), N'mut chuoi phong hat dieu 170gr.jpg')
INSERT [dbo].[SANPHAM] ([MASP], [TENSP], [LOAI], [SOLUONG], [MANCC], [DONVITINH], [GIAVON], [GIABAN], [HINHANH]) 
VALUES ('', N'Mứt Chuối Phồng Mãng Cầu 220gr', N'Mứt', 0, N'NCC0009', N'Hộp', CAST(43000 AS Decimal(18, 0)), CAST(45000 AS Decimal(18, 0)), N'mut chuoi phong mang cau 220gr.jpg')
INSERT [dbo].[SANPHAM] ([MASP], [TENSP], [LOAI], [SOLUONG], [MANCC], [DONVITINH], [GIAVON], [GIABAN], [HINHANH]) 
VALUES ('', N'Mứt Chuối Phồng Mãng Cầu 150gr', N'Mứt', 0, N'NCC0009', N'Hộp', CAST(33000 AS Decimal(18, 0)), CAST(35000 AS Decimal(18, 0)), N'mut chuoi phong mang cau 150gr.jpg')
INSERT [dbo].[SANPHAM] ([MASP], [TENSP], [LOAI], [SOLUONG], [MANCC], [DONVITINH], [GIAVON], [GIABAN], [HINHANH]) 
VALUES ('', N'Mứt Chuối Phồng Đậu Phộng 170gr', N'Mứt', 0, N'NCC0009', N'Hộp', CAST(28000 AS Decimal(18, 0)), CAST(30000 AS Decimal(18, 0)), N'mut chuoi phong dau phong 170gr.jpg')

/************************RANEE*******************************/
INSERT [dbo].[SANPHAM] ([MASP], [TENSP], [LOAI], [SOLUONG], [MANCC], [DONVITINH], [GIAVON], [GIABAN], [HINHANH]) 
VALUES ('', N'Dầu Cá 250ml', N'Dầu Ăn', 0, N'NCC0010', N'Chai', CAST(14000 AS Decimal(18, 0)), CAST(15000 AS Decimal(18, 0)), N'dau ranee 250ml.jpg')
INSERT [dbo].[SANPHAM] ([MASP], [TENSP], [LOAI], [SOLUONG], [MANCC], [DONVITINH], [GIAVON], [GIABAN], [HINHANH]) 
VALUES ('', N'Dầu Cá Cao Cấp 950ml', N'Dầu Ăn', 0, N'NCC0010', N'Chai', CAST(43000 AS Decimal(18, 0)), CAST(45000 AS Decimal(18, 0)), N'dau ranee 950ml.jpg')

/*************************GẠO CỎ MAY***************************/
INSERT [dbo].[SANPHAM] ([MASP], [TENSP], [LOAI], [SOLUONG], [MANCC], [DONVITINH], [GIAVON], [GIABAN], [HINHANH]) 
VALUES ('', N'Gạo Cỏ May - Jasmine 1kg', N'Gạo', 0, N'NCC0011', N'Gói', CAST(33000 AS Decimal(18, 0)), CAST(35000 AS Decimal(18, 0)), N'gao jasmine 1kg.jpg')
INSERT [dbo].[SANPHAM] ([MASP], [TENSP], [LOAI], [SOLUONG], [MANCC], [DONVITINH], [GIAVON], [GIABAN], [HINHANH]) 
VALUES ('', N'Gạo Cỏ May - Lotus 1kg', N'Gạo', 0, N'NCC0011', N'Gói', CAST(33000 AS Decimal(18, 0)), CAST(35000 AS Decimal(18, 0)), N'gao lotus 1kg.jpg')
INSERT [dbo].[SANPHAM] ([MASP], [TENSP], [LOAI], [SOLUONG], [MANCC], [DONVITINH], [GIAVON], [GIABAN], [HINHANH]) 
VALUES ('', N'Gạo Long Châu 5kg', N'Gạo', 0, N'NCC0011', N'Gói', CAST(155000 AS Decimal(18, 0)), CAST(160000 AS Decimal(18, 0)), N'gao long chau 5kg.jpg')
INSERT [dbo].[SANPHAM] ([MASP], [TENSP], [LOAI], [SOLUONG], [MANCC], [DONVITINH], [GIAVON], [GIABAN], [HINHANH]) 
VALUES ('', N'Gạo Bốn Mùa 5kg', N'Gạo', 0, N'NCC0011', N'Gói', CAST(110000 AS Decimal(18, 0)), CAST(115000 AS Decimal(18, 0)), N'gao bon mua 5kg.jpg')
INSERT [dbo].[SANPHAM] ([MASP], [TENSP], [LOAI], [SOLUONG], [MANCC], [DONVITINH], [GIAVON], [GIABAN], [HINHANH]) 
VALUES ('', N'Gạo Jasmine 5kg', N'Gạo', 0, N'NCC0011', N'Gói', CAST(150000 AS Decimal(18, 0)), CAST(155000 AS Decimal(18, 0)), N'gao jasmine 5kg.jpg')
INSERT [dbo].[SANPHAM] ([MASP], [TENSP], [LOAI], [SOLUONG], [MANCC], [DONVITINH], [GIAVON], [GIABAN], [HINHANH]) 
VALUES ('', N'Gạo Ngọc Sa 5kg', N'Gạo', 0, N'NCC0011', N'Gói', CAST(135000 AS Decimal(18, 0)), CAST(140000 AS Decimal(18, 0)), N'gao ngoc sa 5kg.jpg')

/************************CÔNG TY LƯƠNG THỰC*******************/
INSERT [dbo].[SANPHAM] ([MASP], [TENSP], [LOAI], [SOLUONG], [MANCC], [DONVITINH], [GIAVON], [GIABAN], [HINHANH]) 
VALUES ('', N'Gạo Ramsar 5kg', N'Gạo', 0, N'NCC0012', N'Gói', CAST(95000 AS Decimal(18, 0)), CAST(100000 AS Decimal(18, 0)), N'gao ramsar 5kg.jpg')
INSERT [dbo].[SANPHAM] ([MASP], [TENSP], [LOAI], [SOLUONG], [MANCC], [DONVITINH], [GIAVON], [GIABAN], [HINHANH]) 
VALUES ('', N'Gạo Tháp Mười 3kg', N'Gạo', 0, N'NCC0012', N'Gói', CAST(75000 AS Decimal(18, 0)), CAST(77000 AS Decimal(18, 0)), N'gao thap muoi 3kg.jpg')
INSERT [dbo].[SANPHAM] ([MASP], [TENSP], [LOAI], [SOLUONG], [MANCC], [DONVITINH], [GIAVON], [GIABAN], [HINHANH]) 
VALUES ('', N'Gạo Tràm Chim 3kg', N'Gạo', 0, N'NCC0012', N'Gói', CAST(77000 AS Decimal(18, 0)), CAST(80000 AS Decimal(18, 0)), N'gao tram chim 3kg.jpg')


INSERT SANPHAM (MASP, TENSP, LOAI, SOLUONG, MANCC, DONVITINH, GIAVON, GIABAN, HINHANH)
VALUES()


/********KHACH HANG*************/
INSERT KHACHHANG (MAKH, TK, MK, TENKH, EMAILKH, DIACHIKH, DTKH, GIOITINH)
VALUES('', 'dndphu', '123456', N'Đình Phú', 'dndphu@gmail.com', N'Bình Thạnh, TP. HCM', '01689 727217', 'Nam')
INSERT KHACHHANG (MAKH, TK, MK, TENKH, EMAILKH, DIACHIKH, DTKH, GIOITINH)
VALUES('', 'ledinhmanh07', '123456', N'Đình Mạnh', 'ledinhmanh07@gmail.com', N'Bình Thạnh, TP. HCM', '08 9999 1024', 'Nam')
INSERT KHACHHANG (MAKH, TK, MK, TENKH, EMAILKH, DIACHIKH, DTKH, GIOITINH)
VALUES('', 'dzu2801', '123456', N'Đình Dzu', 'dzu2801@gmail.com', N'Quận 8, TP. HCM', '0901 010709', 'Nam')

INSERT KHACHHANG (MAKH, TK, MK, TENKH, EMAILKH, DIACHIKH, DTKH, GIOITINH)
VALUES()